package com.lightevents.payments;
import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient; import java.math.*; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.util.*;
@RestController @RequestMapping("/api/payments")
public class PaymentController { private final TransactionRepository repo; private final RestClient rest=RestClient.create(); @Value("${stripe.secret-key:}") private String stripeKey; @Value("${paypal.client-id:}") private String paypalClientId; @Value("${paypal.client-secret:}") private String paypalClientSecret; @Value("${paypal.base-url:https://api-m.paypal.com}") private String paypalBaseUrl; @Value("${app.frontend-url:http://localhost:5173}") private String frontendUrl; public PaymentController(TransactionRepository repo){this.repo=repo;}
 public record InitiatePaymentRequest(@NotNull Long eventId, Long attendeeId, String reservationReference, @NotNull PaymentProvider provider, @NotNull @DecimalMin("0.01") BigDecimal amount, String currency, String payerPhone) {}
 public record CheckoutResponse(String reference, PaymentProvider provider, PaymentStatus status, BigDecimal gross, BigDecimal platformFee, BigDecimal organizerNet, String checkoutUrl, String note) {}
 @PostMapping({"/mobile-money/initiate","/checkout"}) public CheckoutResponse initiate(@RequestBody InitiatePaymentRequest r){ BigDecimal gross=r.amount(); BigDecimal fee=gross.multiply(new BigDecimal("0.045")).setScale(2, RoundingMode.HALF_UP); Transaction t=new Transaction(); t.setEventId(r.eventId()); t.setAttendeeId(r.attendeeId()); t.setReservationReference(r.reservationReference()); t.setProvider(r.provider()); t.setAmount(gross); t.setPlatformFee(fee); t.setOrganizerNet(gross.subtract(fee)); t.setCurrency(r.currency()==null?"EUR":r.currency()); t.setPayerPhone(r.payerPhone()); t.setStatus(PaymentStatus.PENDING); String url=checkoutUrl(t); t.setCheckoutUrl(url); t=repo.save(t); return new CheckoutResponse(t.getReference(), t.getProvider(), t.getStatus(), t.getAmount(), t.getPlatformFee(), t.getOrganizerNet(), t.getCheckoutUrl(), "LightEvents encaisse, garde 4.5%, puis prépare le reversement automatique vers le moyen choisi par l'organisateur."); }
 private String checkoutUrl(Transaction t){ if(t.getProvider()==PaymentProvider.STRIPE && !blank(stripeKey)) return createStripeCheckout(t); if(t.getProvider()==PaymentProvider.PAYPAL && !blank(paypalClientId) && !blank(paypalClientSecret)) return createPaypalOrder(t); return frontendUrl+"/tickets?paymentPreview="+t.getProvider()+"&amount="+t.getAmount(); }
 private String createStripeCheckout(Transaction t){ try{ String body="mode=payment&success_url="+enc(frontendUrl+"/tickets?paid=true")+"&cancel_url="+enc(frontendUrl+"/events/"+t.getEventId())+"&line_items[0][quantity]=1&line_items[0][price_data][currency]="+enc(t.getCurrency().toLowerCase())+"&line_items[0][price_data][unit_amount]="+t.getAmount().multiply(BigDecimal.valueOf(100)).setScale(0,RoundingMode.HALF_UP)+"&line_items[0][price_data][product_data][name]="+enc("Ticket LightEvents"); Map res=rest.post().uri("https://api.stripe.com/v1/checkout/sessions").headers(h->{h.setBearerAuth(stripeKey);h.set("Content-Type","application/x-www-form-urlencoded");}).body(body).retrieve().body(Map.class); return String.valueOf(res.get("url")); }catch(Exception e){ return frontendUrl+"/tickets?stripePreview=true"; }}
 private String createPaypalOrder(Transaction t){ try{ Map token=rest.post().uri(paypalBaseUrl+"/v1/oauth2/token").headers(h->{h.setBasicAuth(paypalClientId, paypalClientSecret);h.set("Content-Type","application/x-www-form-urlencoded");}).body("grant_type=client_credentials").retrieve().body(Map.class); String access=String.valueOf(token.get("access_token")); Map<String,Object> amount=Map.of("currency_code", t.getCurrency(), "value", t.getAmount().setScale(2,RoundingMode.HALF_UP).toPlainString()); Map<String,Object> body=Map.of("intent","CAPTURE","purchase_units",List.of(Map.of("reference_id",t.getReference(),"description","Ticket LightEvents","custom_id",t.getReference(),"amount",amount)),"application_context",Map.of("return_url",frontendUrl+"/tickets?paypalPaid=true","cancel_url",frontendUrl+"/events/"+t.getEventId())); Map res=rest.post().uri(paypalBaseUrl+"/v2/checkout/orders").headers(h->{h.setBearerAuth(access);h.set("Content-Type","application/json");h.set("Prefer","return=representation");}).body(body).retrieve().body(Map.class); t.setProviderReference(String.valueOf(res.get("id"))); for(Object link:(List)res.getOrDefault("links",List.of())){ Map l=(Map)link; if("approve".equals(l.get("rel"))) return String.valueOf(l.get("href")); } return frontendUrl+"/tickets?paypalOrder="+res.get("id"); }catch(Exception e){ return frontendUrl+"/tickets?paypalPreview=true"; }}
 private static boolean blank(String v){return v==null||v.isBlank();} private static String enc(String s){return URLEncoder.encode(s, StandardCharsets.UTF_8);} }
