package com.lightevents.support;
import com.lightevents.ai.OpenAiService; import com.lightevents.events.*; import com.lightevents.notifications.NotificationService; import jakarta.validation.Valid; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/support")
public class SupportController { private final OpenAiService ai; private final EventRepository events; private final TicketTypeRepository tickets; private final Optional<NotificationService> notifications; public SupportController(OpenAiService ai, EventRepository events, TicketTypeRepository tickets, Optional<NotificationService> notifications){this.ai=ai;this.events=events;this.tickets=tickets;this.notifications=notifications;}
 public record ChatRequest(String message) {}
 @GetMapping("/faq") public List<Map<String,String>> faq(){ return List.of(Map.of("q","Comment recevoir mes tickets ?","a","Par email, WhatsApp ou SMS selon votre choix. Pour un événement en ligne, le lien est aussi encodé dans le QR code du ticket."),Map.of("q","Quels moyens de paiement sont disponibles ?","a","Actuellement PayPal et Stripe. Stripe peut couvrir carte bancaire, Apple Pay et Klarna selon la configuration du compte."),Map.of("q","Comment contacter un organisateur ?","a","Ouvrez la page détails de l’événement puis utilisez le formulaire Contacter l’organisateur.")); }
 @PostMapping("/chatbot") public Map<String,Object> chatbot(@RequestBody ChatRequest r){ String msg=r.message()==null?"":r.message(); String context=events.findByStatusOrderByStartsAtAsc(EventStatus.PUBLISHED).stream().limit(25).map(e->e.getTitle()+" | "+e.getCity()+", "+e.getCountry()+" | "+e.getAllowedPaymentMethods()+" | tickets="+e.getTickets().stream().map(t->t.getName()+":"+t.getPrice()+" "+t.getCurrency()+" reste="+(t.getQuantity()-t.getSold())).toList()).toList().toString(); String prompt="Tu es le chatbot LightEvents. Réponds aux questions des visiteurs sur événements existants, lieux, billets disponibles, prix, paiements, tickets et fonctionnement du site. Si tu ne sais pas, propose de consulter la page de l'événement ou le formulaire contact organisateur. Evénements: "+context+"\nQuestion: "+msg; return Map.of("answer",ai.chat(prompt),"handoff","LIGHTEVENTS_AI"); }
 @PostMapping("/events/{id}/contact-organizer") public Map<String,Object> contactOrganizer(@PathVariable Long id, @Valid @RequestBody EventDtos.ContactOrganizerRequest r){ Event e=events.findById(id).orElseThrow(); String body="Demande de contact depuis LightEvents\nÉvénement: "+e.getTitle()+"\nNom: "+r.fullName()+"\nEmail: "+safe(r.email())+"\nTéléphone: "+safe(r.phone())+"\nWhatsApp: "+safe(r.whatsapp())+"\nPays: "+safe(r.countryOfResidence())+"\nMessage: "+safe(r.message()); notifications.ifPresent(n->{ try{ n.sendEmail(e.getOrganizerEmail(), "Contact organisateur - "+e.getTitle(), body); if(e.getOrganizerAccount()!=null) n.sendWhatsApp(e.getOrganizerAccount().getWhatsappNumber(), body); }catch(Exception ignored){} }); return Map.of("sent",true,"message","Votre demande a été envoyée à l’organisateur. Il pourra vous recontacter plus tard."); }
 private static String safe(String v){return v==null?"":v;}
}
