package com.lightevents.support;
import com.lightevents.ai.OpenAiService; import com.lightevents.events.*; import com.lightevents.notifications.NotificationService; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/support")
public class SupportController { private final OpenAiService ai; private final EventRepository events; private final Optional<NotificationService> notifications; public SupportController(OpenAiService ai, EventRepository events, Optional<NotificationService> notifications){this.ai=ai;this.events=events;this.notifications=notifications;}
 public record ChatRequest(String message, String eventName, String visitorName, String visitorEmail, String visitorWhatsapp, String visitorPhone, String countryOfResidence, boolean waitedMoreThanFiveMinutes) {}
 @GetMapping("/faq") public List<Map<String,String>> faq(){ return List.of(Map.of("q","Comment recevoir mes tickets ?","a","Par email, WhatsApp ou SMS selon votre choix. Pour un événement en ligne, le lien est aussi encodé dans le QR code du ticket."),Map.of("q","Combien LightEvents prélève ?","a","4,5% sur les paiements encaissés, puis reversement automatique à l'organisateur."),Map.of("q","Puis-je contacter l'organisateur ?","a","Oui: donnez le nom de l’événement au chatbot, il ouvre une conversation privée et notifie l’organisateur.")); }
 @PostMapping("/chatbot") public Map<String,Object> chatbot(@RequestBody ChatRequest r){ String msg=r.message()==null?"":r.message(); Optional<Event> event = findEvent(r.eventName()!=null&&!r.eventName().isBlank()?r.eventName():msg); if(event.isPresent()){ Event e=event.get(); String room="Conversation privée ouverte pour: "+e.getTitle(); String body="Nouveau contact LightEvents pour votre événement: "+e.getTitle()+"\nMessage: "+msg+"\nNom: "+safe(r.visitorName())+"\nEmail: "+safe(r.visitorEmail())+"\nWhatsApp: "+safe(r.visitorWhatsapp())+"\nTéléphone: "+safe(r.visitorPhone())+"\nPays: "+safe(r.countryOfResidence()); notifications.ifPresent(n->{ try{ n.sendEmail(e.getOrganizerEmail(), "Nouveau chat LightEvents - "+e.getTitle(), body); }catch(Exception ignored){} }); return Map.of("answer", room+". L'organisateur reçoit une notification par mail/WhatsApp. S’il ne répond pas après 5 minutes, laissez votre email ou WhatsApp et je lui transfère.","handoff","ORGANIZER_PRIVATE_CHAT","eventId",e.getId(),"organizerEmail",e.getOrganizerEmail()==null?"":e.getOrganizerEmail()); }
  if(r.waitedMoreThanFiveMinutes()){ String body="Visiteur en attente de plus de 5 minutes. Contact: "+safe(r.visitorName())+" / "+safe(r.visitorEmail())+" / "+safe(r.visitorWhatsapp())+" / "+safe(r.visitorPhone())+" / "+safe(r.countryOfResidence())+"\nMessage: "+msg; notifications.ifPresent(n->{ try{ n.sendEmail("valereyoubi@gmx.de", "Contact chatbot LightEvents à rappeler", body); }catch(Exception ignored){} }); return Map.of("answer","Merci. J’ai envoyé vos coordonnées à l’organisateur. Il pourra vous répondre par email ou WhatsApp.","handoff","CONTACT_COLLECTED"); }
  return Map.of("answer",ai.chat("Réponds comme chatbot LightEvents. Si l'utilisateur veut parler à un organisateur, demande seulement le nom exact de l'événement. Question: "+msg),"handoff","LIGHTEVENTS_AI"); }
 private Optional<Event> findEvent(String q){ if(q==null||q.isBlank()) return Optional.empty(); String needle=q.toLowerCase(); return events.findByStatusOrderByStartsAtAsc(EventStatus.PUBLISHED).stream().filter(e->needle.contains(e.getTitle().toLowerCase())||e.getTitle().toLowerCase().contains(needle)).findFirst(); }
 private static String safe(String v){return v==null?"":v;}
}
