package com.lightevents.invoices;
import com.lightevents.events.*; import com.lightevents.notifications.NotificationService; import org.springframework.stereotype.Service; import java.nio.charset.StandardCharsets; import java.time.format.DateTimeFormatter; import java.util.*;
@Service
public class InvoiceService { private final InvoiceRepository invoices; private final EventRepository events; private final Optional<NotificationService> notifications; public InvoiceService(InvoiceRepository invoices, EventRepository events, Optional<NotificationService> notifications){this.invoices=invoices;this.events=events;this.notifications=notifications;}
 public Invoice createForReservation(Reservation r){ return invoices.findByReservationReference(r.getReference()).orElseGet(()->{ Event e=events.findById(r.getEventId()).orElse(null); Invoice inv=new Invoice(); inv.setInvoiceNumber("LE-"+System.currentTimeMillis()); inv.setReservationReference(r.getReference()); inv.setEventId(r.getEventId()); inv.setBuyerName(r.getBuyerName()); inv.setBuyerEmail(r.getBuyerEmail()); inv.setBuyerPhone(r.getBuyerPhone()); inv.setBuyerWhatsapp(r.getBuyerWhatsapp()); inv.setCompanyPurchase(r.isCompanyPurchase()); inv.setCompanyName(r.getCompanyName()); inv.setGrossAmount(r.getGrossAmount()); inv.setPlatformFee(r.getPlatformFee()); inv.setOrganizerNet(r.getOrganizerNet()); inv.setCurrency("EUR"); inv.setPdfBase64(Base64.getEncoder().encodeToString(pdfBytes(inv,e,r))); inv=invoices.save(inv); Invoice finalInv=inv; notifications.ifPresent(n->{ try{ n.sendEmailWithAttachment(finalInv.getBuyerEmail(), "Facture LightEvents "+finalInv.getInvoiceNumber(), "Merci pour votre achat. Votre facture PDF est jointe.", "facture-"+finalInv.getInvoiceNumber()+".pdf", Base64.getDecoder().decode(finalInv.getPdfBase64())); }catch(Exception ignored){} }); return inv; }); }
 private byte[] pdfBytes(Invoice inv, Event e, Reservation r){ String title=e==null?"Événement LightEvents":e.getTitle(); String text="%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n4 0 obj<</Length 460>>stream\nBT /F1 14 Tf 50 740 Td (Facture LightEvents: "+safe(inv.getInvoiceNumber())+") Tj 0 -28 Td (Evenement: "+safe(title)+") Tj 0 -24 Td (Acheteur: "+safe(inv.getBuyerName())+") Tj 0 -24 Td (Email: "+safe(inv.getBuyerEmail())+") Tj 0 -24 Td (Entreprise: "+(r.isCompanyPurchase()?safe(r.getCompanyName()):"Non")+") Tj 0 -24 Td (Reservation: "+safe(r.getReference())+") Tj 0 -24 Td (Montant: "+r.getGrossAmount()+" "+safe(inv.getCurrency())+") Tj 0 -24 Td (Frais LightEvents 4.5%: "+r.getPlatformFee()+") Tj 0 -24 Td (Net organisateur: "+r.getOrganizerNet()+") Tj ET\nendstream endobj\n5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\nxref\n0 6\n0000000000 65535 f \ntrailer<</Root 1 0 R/Size 6>>\nstartxref\n650\n%%EOF"; return text.getBytes(StandardCharsets.ISO_8859_1); }
 public List<Invoice> byIdentifier(String channel,String destination){ if("phone".equalsIgnoreCase(channel)) return invoices.findByBuyerPhoneOrderByCreatedAtDesc(destination); if("whatsapp".equalsIgnoreCase(channel)) return invoices.findByBuyerWhatsappOrderByCreatedAtDesc(destination); return invoices.findByBuyerEmailIgnoreCaseOrderByCreatedAtDesc(destination); }
 private static String safe(String s){return s==null?"":s.replace("(","[").replace(")","]");}
}
